// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/examples/api/default/proto/api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/examples/api/default/proto/api.proto

It has these top-level messages:
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import go_micro_api "github.com/micro/go-api/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Example service

type ExampleClient interface {
	Call(ctx context.Context, in *go_micro_api.Request, opts ...client.CallOption) (*go_micro_api.Response, error)
}

type exampleClient struct {
	c           client.Client
	serviceName string
}

func NewExampleClient(serviceName string, c client.Client) ExampleClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "example"
	}
	return &exampleClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *exampleClient) Call(ctx context.Context, in *go_micro_api.Request, opts ...client.CallOption) (*go_micro_api.Response, error) {
	req := c.c.NewRequest(c.serviceName, "Example.Call", in)
	out := new(go_micro_api.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Example service

type ExampleHandler interface {
	Call(context.Context, *go_micro_api.Request, *go_micro_api.Response) error
}

func RegisterExampleHandler(s server.Server, hdlr ExampleHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Example{hdlr}, opts...))
}

type Example struct {
	ExampleHandler
}

func (h *Example) Call(ctx context.Context, in *go_micro_api.Request, out *go_micro_api.Response) error {
	return h.ExampleHandler.Call(ctx, in, out)
}

// Client API for Foo service

type FooClient interface {
	Bar(ctx context.Context, in *go_micro_api.Request, opts ...client.CallOption) (*go_micro_api.Response, error)
}

type fooClient struct {
	c           client.Client
	serviceName string
}

func NewFooClient(serviceName string, c client.Client) FooClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "foo"
	}
	return &fooClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *fooClient) Bar(ctx context.Context, in *go_micro_api.Request, opts ...client.CallOption) (*go_micro_api.Response, error) {
	req := c.c.NewRequest(c.serviceName, "Foo.Bar", in)
	out := new(go_micro_api.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Foo service

type FooHandler interface {
	Bar(context.Context, *go_micro_api.Request, *go_micro_api.Response) error
}

func RegisterFooHandler(s server.Server, hdlr FooHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Foo{hdlr}, opts...))
}

type Foo struct {
	FooHandler
}

func (h *Foo) Bar(ctx context.Context, in *go_micro_api.Request, out *go_micro_api.Response) error {
	return h.FooHandler.Bar(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/micro/examples/api/default/proto/api.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4d, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xcd, 0x4c, 0x2e, 0xca, 0xd7, 0x4f, 0xad, 0x48,
	0xcc, 0x2d, 0xc8, 0x49, 0x2d, 0xd6, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0x49, 0x4d, 0x4b, 0x2c, 0xcd,
	0x29, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x07, 0x89, 0xe8, 0x81, 0x59, 0x52, 0xea, 0x18, 0xda,
	0xd2, 0xf3, 0x75, 0x41, 0x1a, 0xd0, 0x14, 0x1a, 0x39, 0x71, 0xb1, 0xbb, 0x42, 0x0c, 0x14, 0x32,
	0xe7, 0x62, 0x71, 0x4e, 0xcc, 0xc9, 0x11, 0x12, 0xd5, 0x4b, 0xcf, 0xd7, 0x03, 0x6b, 0xd2, 0x03,
	0xa9, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x91, 0x12, 0x43, 0x17, 0x2e, 0x2e, 0xc8, 0xcf,
	0x2b, 0x4e, 0x55, 0x62, 0x30, 0xb2, 0xe5, 0x62, 0x76, 0xcb, 0xcf, 0x17, 0x32, 0xe3, 0x62, 0x76,
	0x4a, 0x2c, 0x22, 0x59, 0x7b, 0x12, 0x1b, 0xd8, 0x25, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xad, 0x04, 0x32, 0xe2, 0xeb, 0x00, 0x00, 0x00,
}
